--1. Create an ‘Orders’ table which comprises of these columns – ‘order_id’, ‘order_date’, ‘amount’, ‘customer_id’
CREATE TABLE ORDERS (ORDER_ID INT, ORDER_DATE DATE, AMOUNT INT, CUSTOMER_ID INT)

SELECT * FROM ORDERS

INSERT INTO ORDERS VALUES (1, '2023/01/12', 1000, 1)
INSERT INTO ORDERS VALUES (2, '2023/01/13', 2000, 2)
INSERT INTO ORDERS VALUES (3, '2023/01/14', 3000, 3)
INSERT INTO ORDERS VALUES (4, '2023/01/15', 4000, 4)
INSERT INTO ORDERS VALUES (5, '2023/01/16', 5000, 5)
INSERT INTO ORDERS VALUES (6, '2023/01/17', 6000, 6)
INSERT INTO ORDERS VALUES (7, '2023/01/18', 7000, 7)
INSERT INTO ORDERS VALUES (8, '2023/01/19', 8000, 8)
INSERT INTO ORDERS VALUES (9, '2023/01/20', 9000, 9)


--2. Make an inner join on ‘Customer’ & ‘Order’ tables on the ‘customer_id’ column
CREATE TABLE CUSTOMER (CUSTOMER_ID INT, FIRST_NAME VARCHAR(50), LAST_NAME VARCHAR(50), EMAIL VARCHAR(50) UNIQUE, ADDRESS NVARCHAR(200), CITY VARCHAR(50), 
						STATE VARCHAR(50), ZIP INT)

Select * from CUSTOMER

SELECT ORDERS.CUSTOMER_ID, orders.ORDER_DATE, orders.AMOUNT, orders.ORDER_ID, customer.FIRST_NAME, customer.LAST_NAME, customer.ADDRESS, customer.CITY,	CUSTOMER.STATE, customer.ZIP
FROM ORDERS INNER JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID 

-- 3. Make left and right joins on ‘Customer’ & ‘Order’ tables on the ‘customer_id’ column
--Left Join
SELECT ORDERS.ORDER_DATE, ORDERS.AMOUNT, ORDERS.ORDER_ID, CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME, CUSTOMER.ADDRESS, CUSTOMER.CITY,	CUSTOMER.STATE, CUSTOMER.ZIP 
FROM ORDERS LEFT JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID 

--Right Join
SELECT orders.ORDER_DATE, orders.AMOUNT, orders.ORDER_ID, customer.FIRST_NAME, customer.LAST_NAME, customer.ADDRESS, customer.CITY,	CUSTOMER.STATE, customer.ZIP 
FROM ORDERS RIGHT JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID 

-- 4. Update the ‘Orders’ table, set the amount to be 100 where ‘customer_id’ is 3
update orders 
set AMOUNT=100
where customer_id = 3

Select * from ORDERS